from app.models.schemas import ChangedFile, Finding, PrInfo, Summary, TestSuggestion


def build_github_comment(
    pr: PrInfo,
    summary: Summary,
    files: list[ChangedFile],
    findings: list[Finding],
    test_suggestions: list[TestSuggestion],
) -> str:
    risk_lines = "\n".join(
        f"- `{file.filename}`: {file.risk_level} ({file.risk_score}) - {', '.join(file.risk_reasons[:2])}"
        for file in files[:5]
    )
    finding_lines = "\n".join(
        (
            f"- **{finding.severity} {finding.title}** "
            f"(`{finding.file}:{finding.line}`, confidence {finding.confidence:.0%})\n"
            f"  - Impact: {finding.impact}\n"
            f"  - Suggestion: {finding.suggestion}"
        )
        for finding in findings[:8]
    )
    test_lines = "\n".join(
        f"- **{item.title}**: {item.suggested_case}" for item in test_suggestions[:5]
    )

    return "\n".join(
        [
            "## AI PR Review Summary",
            "",
            f"PR: {pr.owner}/{pr.repo}#{pr.number} - {pr.title}",
            "",
            "### What changed",
            summary.what_changed,
            "",
            "### Risk overview",
            summary.risk_overview,
            "",
            "### Review focus",
            ", ".join(summary.review_focus),
            "",
            "### High-risk files",
            risk_lines or "- No notable file risk identified.",
            "",
            "### Findings",
            finding_lines or "- No evidence-backed findings after verification.",
            "",
            "### Test suggestions",
            test_lines or "- No additional test suggestions.",
            "",
            "_Generated by AI PR Review demo. Review before posting._",
        ]
    )
