DEMO_REPORT = {
    "report_id": "demo-report",
    "status": "completed",
    "pr": {
        "owner": "demo-org",
        "repo": "checkout-service",
        "number": 42,
        "title": "Relax payment permission check and add order lookup",
        "description": "Demo PR with intentionally reviewable risk signals.",
        "author": "demo-dev",
        "base_branch": "main",
        "head_branch": "feature/payment-fast-path",
        "html_url": "https://github.com/demo-org/checkout-service/pull/42",
        "commits": [{"sha": "demo", "message": "Add fast payment path", "author": "demo-dev"}],
    },
    "summary": {
        "what_changed": "This PR changes payment authorization and adds an order lookup path.",
        "risk_overview": "Two high-risk files were identified because the change touches payment, permission, database, and error handling behavior without a matching test update.",
        "review_focus": ["permissions", "data correctness", "test coverage", "error handling"],
    },
    "file_risks": [
        {
            "filename": "src/payment/authorize.ts",
            "status": "modified",
            "additions": 28,
            "deletions": 9,
            "patch": "@@ -21,6 +21,13 @@\n+if (!user.role) {\n+  return true;\n+}\n+return hasPermission(user, 'payment:write');",
            "risk_level": "critical",
            "risk_score": 92,
            "risk_reasons": [
                "touches payment code",
                "changes access-control related logic",
                "adds permissive or nullable early return",
                "no test file changed in this PR",
            ],
        },
        {
            "filename": "src/orders/repository.ts",
            "status": "modified",
            "additions": 34,
            "deletions": 4,
            "patch": "@@ -10,3 +10,9 @@\n+const result = await db.query(`SELECT * FROM orders WHERE id = ${id}`);\n+return result.rows[0];",
            "risk_level": "high",
            "risk_score": 78,
            "risk_reasons": [
                "adds SQL or database query logic",
                "changes error handling behavior",
                "no test file changed in this PR",
            ],
        },
    ],
    "findings": [
        {
            "title": "Permission check can allow users with missing roles",
            "severity": "P1",
            "confidence": 0.86,
            "category": "security",
            "file": "src/payment/authorize.ts",
            "line": 22,
            "evidence": "The new branch returns true when user.role is missing.",
            "impact": "Requests without a role may bypass the normal payment permission check.",
            "suggestion": "Change the missing-role branch to deny access and add regression tests for missing, normal, and admin roles.",
            "comment_draft": "This early return appears to allow payment writes when `user.role` is missing. Can we make this deny-by-default and add role coverage?",
        },
        {
            "title": "Order lookup builds SQL from raw id",
            "severity": "P1",
            "confidence": 0.79,
            "category": "security",
            "file": "src/orders/repository.ts",
            "line": 11,
            "evidence": "The SQL string interpolates id directly into the query.",
            "impact": "A crafted id could change the query semantics if the route does not validate it first.",
            "suggestion": "Use a parameterized query and test malicious and empty id inputs.",
            "comment_draft": "This query should use parameters instead of interpolating `id` directly into SQL.",
        },
        {
            "title": "Behavior change has no matching test update",
            "severity": "P2",
            "confidence": 0.74,
            "category": "test",
            "file": "src/payment/authorize.ts",
            "line": 22,
            "evidence": "No test file changed in the PR.",
            "impact": "The permission behavior may regress without automated coverage.",
            "suggestion": "Add tests for missing role, unauthorized user, and authorized payment writer.",
            "comment_draft": "I do not see matching test coverage for the changed permission path.",
        },
    ],
    "test_suggestions": [
        {
            "title": "Add payment authorization regression tests",
            "reason": "The PR changes access control in payment code.",
            "suggested_case": "Assert missing roles are denied and users require payment:write.",
        },
        {
            "title": "Add order lookup input tests",
            "reason": "The PR adds SQL-backed order lookup behavior.",
            "suggested_case": "Cover normal id, empty id, and SQL-like malicious input.",
        },
    ],
    "github_comment_markdown": "## AI PR Review Summary\n\nPR: demo-org/checkout-service#42 - Relax payment permission check and add order lookup\n\n### What changed\nThis PR changes payment authorization and adds an order lookup path.\n\n### Findings\n- **P1 Permission check can allow users with missing roles** (`src/payment/authorize.ts:22`)\n- **P1 Order lookup builds SQL from raw id** (`src/orders/repository.ts:11`)\n\n_Generated by AI PR Review demo. Review before posting._",
}
